### ISSUE TITLE
Guidelines color code

### ISSUE THREAD

**Issue by Midnighter** [MetabolicAtlas/standard-GEM#12]
It is very hard to distinguish

> 🟧 Recommendations: should, should not
> 🟨 Possibility and capability: can

maybe you can consider a blue tone or so for _can_. Also I'm not sure how colour blind safe the entire scale is.

**Comment by mihai-sysbio** [comment]
I'm totally up for changing the colors.

To enable colors in markdown I've relied on square emojis, which seem to come in [limited colors](https://emojipedia.org/search/?q=square). I ended up choosing these 3 because they resemble somewhat of gradient.

Here is a preview of how the colors look without saturation.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/23480589/90131489-e7048780-dd74-11ea-8041-e450bfa89555.png">

How does it look?

**Comment by Midnighter** [comment]
Hmm, maybe I had my color red shifted due to night time. Seems all good to me now.
