### ISSUE TITLE
Require tagged releases to Zenodo

### ISSUE THREAD

**Issue by Midnighter** [MetabolicAtlas/standard-GEM#14]
You're doing this for the yeastGEM and I think it's extremely important. Each tagged version (GitHub release) will automatically be deposited on Zenodo via their integration. This makes that exact model available from an unchanging resource and the exact version can be cited with a DOI.

**Comment by mihai-sysbio** [comment]
Personally, I've been struggling with this idea.
On one hand, it's a great solution to the issue of providing storage and DOIs for releases.
On the other, for somebody new to GitHub enabling Zenodo be too daunting.

Currently, this is how this is described in the standard:
> Additionally, the /README.md file should contain Zenodo badge. As soon as the first public release is in made, the repository must be archived via Zenodo, and the corresponding badge be updated. A default is provided in the file.

With a `should` for the badge, and a `must` for Zenodo, the language is a bit unclear. There's also a timing angle - the standard is meant to evolve, so requirements are meant to change, ie we don't have to impose *all* requirements from the beginning.

What would be best - `should` or `must`? Anyway, I think the text description can be improved.

**Comment by Midnighter** [comment]
[This is a pretty clear guide](https://guides.github.com/activities/citable-code/), do you really think it's daunting? I'm obviously biased but I think the possibility to track model use in publication by DOI in future is worth the effort.

**Comment by JonathanRob** [comment]
@Midnighter I must admit that I don't quite understand the advantage of citing a DOI over an exact version number, as is done with other software/packages. However, your point regarding GitHub (Microsoft) having the power to revoke access was enough to convince me.

**Comment by Midnighter** [comment]
I see three key advantages:

* Data on Zenodo is unchangeable and (supposed to be) a permanent record. GitHub tags are easily changed which means if model authors are not careful you may refer to a version of the model that was changed after the fact.
* DOIs fully integrate models in the academic "reward" system of citations. This means that future contributors to models who were not part of the first publication can be acknowledged for their work, too. This is not possible when only citing an initial publication and mentioning a version number.
* DOIs are much more findable. They can be traced through the existing citation network tools. This would allow you to see adoption of your model versions and give you pretty good arguments when applying for funding. Parsing full text literature for version strings to get the same information seems rather infeasible.

**Comment by JonathanRob** [comment]
Great, thanks for the clarification!

**Comment by mihai-sysbio** [comment]
> do you really think it's daunting?

For somebody who just created a GH account, I'd think so. If we come back question of `must` vs `should` - when using Zenodo is a `must`, any repo which aims to follow the standard but lacks this would be deemed as "not standard compliant". In the case of new adopters, it might be too much to ask. With a `should` we recommend using Zenodo, but don't penalize when it's not used. My expectation is that more experienced users would choose Zenodo anyway, simply because of the advantages nicely laid out (thanks @Midnighter, copied over to the [wiki](https://github.com/MetabolicAtlas/standard-GEM/wiki/FAQ#zenodo) for further reference). And maybe in a year or two, with enough adopters, it would make sense to bump this up from a "should" to a "must". Would this sound reasonable, or is it better to go directly to `must`?

**Comment by mihai-sysbio** [comment]
I'm not sure why merging the PR did not close the issue, so I'm closing this manually.
Please reopen if necessary.
