### ISSUE TITLE
name of folder with models

### ISSUE THREAD

**Issue by edkerk** [MetabolicAtlas/standard-GEM#4]
### Description of the issue:
What should be the name of the folder containing the model files?

- `modelFiles`
- `models`
- `model`

Note that option 2 and 3 are in line with the style of the other folders (`code`, `data`).

#### Expected feature/value/output:
`/models` or `/model`

#### Current feature/value/output:
`/modelFiles`

**Comment by BenjaSanchez** [comment]
@edkerk I think `model` would be the best option, in line with e.g. memote repos but also more accurate, as the folder should contain just the one model but in different formats.

BTW have you guys seen https://github.com/opencobra/cookiecutter-memote ? Looks like it's more or less similar to the efforts being done here, maybe would be good to align both standards :)

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez indeed the efforts better be aligned.

Those `Configuration Values` had been mostly implemented in `HumanGEM` as [metadata](https://github.com/SysBioChalmers/Human-GEM/issues/71), which probably could be defined explicitly in `standard-GEM`, aligning with [cookiecutter](https://github.com/opencobra/cookiecutter-memote).

**Comment by edkerk** [comment]
Seems only `model` gets +1 votes, and compatibility with the memote cookiecutter is a strong argument for going for `model`.

**Comment by mihai-sysbio** [comment]
@Hao-Chalmers there is indeed a need to have MIRIAM-style metadata at the model level. To me, neither implementation (config values, Human-GEM metadata) is perfect, but it sounds like there should be a general discussion around this in order to formalize something.  
@BenjaSanchez I really liked what `cookiecutter` aimed to do - basically putting in all the structure in place. And to that end, `standard-GEM` aims this too, while trying to increase transparency.

Summary: we go for `model`.
